"""Take the code blocks defined in example.py, format them with Pygments,
insert the formatted HTML code blocks into the right places in the
index-src.html file and write it all to index.html.

The index-src.html and example.py files are the ones that should be hand-edited.
HTML comments in index-src.html of the form ``<!-- code-block: NAME -->`` will
be replaced by Pygments-formatted code blocks in example.py that are surrounded
by lines of the form ``# start-block: NAME`` and ``# end-block: NAME``.

The index.html file is generated by this script and should *not* be hand-edited.

"""

import codecs
import pprint
from pygments import highlight
from pygments.lexers import PythonLexer
from pygments.formatters import HtmlFormatter

formatter = HtmlFormatter(cssclass="codehilite")

# Get code blocks from example.py
blocks = {}
with codecs.open('example.py', 'r', 'utf-8') as fi:
    inblock = False
    block = []
    block_name = None
    for line in fi:
        if line.startswith('# start-block: '):
            block_name = line.strip().split()[-1]
            inblock = True
            block = []
        elif line.startswith('# end-block: '):
            inblock = False
            blocks[block_name] = u''.join(block)
        elif inblock:
                block.append(line)
# Re-write index.html so that the code block comments are replaced by the
# Pygment-ized code.
with codecs.open('index-src.html', 'r', 'utf-8') as fi:
    with codecs.open('index.html', 'w', 'utf-8') as fo:
        for line in fi:
            line_els = line.strip().split()
            if len(line_els) > 1 and line_els[1] == 'code-block:':
                block_name = line_els[2]
                if block_name in blocks:
                    fo.write(highlight(blocks[block_name], PythonLexer(),
                        formatter))
            else:
                fo.write(line)

